#!/bin/bash
# Download the APOD and archive it:
#
# - The most recently downloaded APOD and text will reside in ~/.APOD/new/
# - The files are archived to ~/.APOD/
# 
# This isn't as smart as apod_get in that it will always re-download an image.
# This is because it always erases the content of 'new/' before doing anything
# else.
# 
# by gammy

path_storage=~/.APOD
path_new=${path_storage}/new

# XXX grrr
font=/home/gammy/code/perl/apod_get/font/Istok-Regular.ttf

trap boom ERR

boom() {
	echo "Fatal error."
	exit 1
}

if [ ! -e ${font} ]; then
	echo "Can't find \"${font}\""
	exit 1
fi

if [ ! -e ${path_storage} ]; then
	mkdir -p ${path_storage} 
fi

if [ ! -e ${path_new} ]; then
	mkdir -p ${path_new}
fi

cd ${path_new}
rm -f ${path_new}/*

echo "(in $(pwd)) Getting the APOD.."
apod_get

cp -f ${path_new}/* ${path_storage}/

# file_txt=$(find      -iname "*.txt" | tail -n1)
# file_src=$(find -not -iname "*.txt" | tail -n1)
