#!/usr/bin/env perl
# Get full-size APOD as well as description.
# Should be run at least once per day.
#
# Takes an APOD URL as optional argument.
#
# It skips the image download if the file already
# exists locally.
#
# by gammy.

use warnings;
use strict;

use APOD;

my $apod = new APOD();

if(@ARGV) {
	$apod->peek(shift(@ARGV)) or die "$!";
} else {
	$apod->peek() or die "$!";
}

# There should always be a description
die "It doesn't seem like we could parse the page" if ! $apod->description;

# No image? - just die.
die "No image found (perhaps it's a video today).\n" if ! $apod->url;

my $img_path = $apod->destination . '/' . $apod->filename;
my $dsc_path = "$img_path.txt";

print "checking $img_path\n";
die "Already got \"$img_path\".\n" if -e $img_path;

$apod->save_image();
print "Saved \"$img_path\"\n";

$apod->save_description();
print "Saved \"$dsc_path\"\n";
