#!/bin/bash
opt_size="--desktop-size" # To hardcode, set to "--size=1920x1024"
path=$HOME/.APOD
latest=$path/latest

if [ ! $DISPLAY ]; then     # DISPLAY isn't set by crontab
	export DISPLAY=:0.0 # (it's needed to get the desktop size)
fi

PATH="$PATH:$(dirname $0)"  # In case we're not globally installed

apod_get --archive \
         --path=$path $1

apod_setbg --text-file="$(ls $latest/*.txt)" \
	   $opt_size \
	   $(find $latest -type l -not -iname "*.txt") \
	   $path/annotated.png
