#!/bin/bash

# XXX the plague!
font=/home/gammy/code/perl/apod_get/font/Istok-Regular.ttf

trap boom ERR

set_background() {
	# Appropriate for gnome
	# Note that gconftool of course needs a full path (not relative)
	gconftool-2 -t str -s /desktop/gnome/background/picture_filename "$1"

	# Appropriate for pekwm, etc
	#hsetroot -center "$1"
	#feh --bg-center "$1"

	return;
}

boom() {
	echo "Fatal error."
	exit 1
}

usage() {
	     echo "Usage: $(basename $0) [-t <text-file>] [-s <WxH>] <input image> <output image>"
	     echo "-t foo.txt        Annotate image with content of 'foo.txt'"
	     echo "-i in.png         Input file : Use 'foo.png' as background"
	     echo "-o out.png        Output file: Output result to 'foo.png'"
	     echo "-s 1024x600       Set result image size to 1024x600"
	     echo
}

opt_text=
file_src=
file_dst=
opt_size="--desktop-size"

while getopts “ht:i:o:s:” opt; do
	case $opt in
		i)
			file_src=$OPTARG
			;;
		o)
			file_dst=$OPTARG
			;;
		t)
			opt_text="--text-file=${OPTARG}"
			;;
		s)
			opt_size="--size=$OPTARG"
			;;
		h)
			usage
			exit
			;;
	esac
done

if [[ -z ${file_src} ]] || [[ -z ${file_dst} ]]; then
	usage
	exit
fi

linnea_annotate ${opt_size} \
		${opt_text} \
		--font-file="${font}" \
		--font-pts=12 \
		--valign=bottom \
                "${file_src}" \
		"${file_dst}"

set_background "${file_dst}"
