#!/bin/bash

font=$(dirname $0)/font/Istok-Regular.ttf

boom() {
	echo "Fatal error."
	exit 1
}

usage() {
	     echo "Usage: $(basename $0) [-t <text-file>] [-s <WxH>] -i <input image> -o <output image>"
	     echo "-t foo.txt        Annotate image with content of 'foo.txt'"
	     echo "-i in.png         Input file : Use 'in.png' as background"
	     echo "-o out.png        Output file: Output result to 'out.png'"
	     echo "-s 1024x600       Set result image size to 1024x600"
	     echo
}

opt_text=
file_src=
file_dst=
opt_size="--desktop-size"

while getopts “ht:i:o:s:” opt; do
	case $opt in
		i)
			file_src=$OPTARG
			;;
		o)
			file_dst=$OPTARG
			;;
		t)
			opt_text="--text-file=${OPTARG}"
			;;
		s)
			opt_size="--size=$OPTARG"
			;;
		h)
			usage
			exit
			;;
	esac
done

if [[ -z ${file_src} ]] || [[ -z ${file_dst} ]]; then
	usage
	exit
fi

if [ ! -f ${font} ]; then
	echo Unable to find \"${font}\": Please edit $0 to specify a working \
	font path.
	exit
fi

linnea_annotate $opt_size \
		$opt_text \
		--font-file="$font" \
		--font-pts=12 \
		--valign=bottom \
                "$file_src" \
		"$file_dst" || boom

if [ "$APOD_BG_SET" ]; then
	echo $APOD_BG_SET \"$file_dst\"
	$APOD_BG_SET "$file_dst" || boom
else
	echo -e "\nEnvironment variable APOD_BG_SET is unset!
Do something like \e[1mexport APOD_BG_SET=\"feh --bg-fill\"\e[0m to set it.
In the meantime, let's try a few alternatives which you might have.\n"

	bgtry[0]='fbsetbg' 
	bgtry[1]='hsetroot -center'
	bgtry[2]='feh --bg-fill'
	bgtry[3]='gconftool-2 -t str -s /desktop/gnome/background/picture_options "zoom"; gconftool-2 -t str -s /desktop/gnome/background/picture_filename'

	failed=1
	for try in "${bgtry[@]}"; do

		APOD_BG_SET="$try"

		echo -n "Trying '$APOD_BG_SET \"$file_dst\"': "
		$APOD_BG_SET "$file_dst"

		if [ $? == 0 ]; then
			failed=0
			echo "Success!"
			break;
		fi
	done

	if [ $failed = 1 ]; then
		echo "Exhausted all tries - GIVING UP."
		exit 1
	fi
fi
