#!/bin/bash
# Download the APOD, annotate it and set it as background.
#
# This script isn't as 'smart' as apod_get itself and will
# always download the APOD regardless of if you already
# have it or not (since it clears the new/ directory
# each time.
# It also assumes apod_get and linnea_annotate are 
# globally installed (available in $PATH)
# by gammy

path_storage=~/.APOD
path_new=${path_storage}/new
file_out=${path_storage}/annotated.png
font=/home/gammy/code/perl/apod_get/font/Istok-Regular.ttf

trap boom ERR

boom() {
	echo "Fatal error."
	exit 1
}

if [ ! -e ${font} ]; then
	echo "Can't find \"${font}\""
	exit 1
fi

if [ ! -e ${path_storage} ]; then
	mkdir -p ${path_storage} 
fi

if [ ! -e ${path_new} ]; then
	mkdir -p ${path_new}
fi

cd ${path_new}
rm -f ${path_new}/*

echo "Getting the APOD.."
apod_get

echo "Archiving.."
cp -f ${path_new}/* ${path_storage}/

file_txt=$(find      -iname "*.txt" | tail -n1)
file_img=$(find -not -iname "*.txt" | tail -n1)

apod_setbg -t ${file_txt} -i ${file_img}
